/* predefine by robotC IDE*/
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,  liftAngleLeft, sensorPotentiometer)
#pragma config(Sensor, in2,  liftAngleRight, sensorPotentiometer)
#pragma config(Sensor, in3,  coneAngleLeft, sensorPotentiometer)
#pragma config(Sensor, in4,  coneAngleRight, sensorPotentiometer)
#pragma config(Sensor, dgtl1, mobileLiftPneumatics, sensorDigitalOut)
#pragma config(Sensor, dgtl2, coneLiftPneumatics, sensorDigitalOut)
#pragma config(Sensor, I2C_1, leftDrive,   sensorQuadEncoderOnI2CPort,  , AutoAssign )
#pragma config(Sensor, I2C_2, rightDrive,   sensorQuadEncoderOnI2CPort,  , AutoAssign )
#pragma config(Sensor, I2C_3, liftLowerLeft, sensorQuadEncoderOnI2CPort,  , AutoAssign )
#pragma config(Sensor, I2C_4, liftLowerRight, sensorQuadEncoderOnI2CPort,  , AutoAssign )
#pragma config(Motor, port1,      driveBackRight, tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor, port2,      driveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor, port3,      liftMobileLowerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_4)
#pragma config(Motor, port4,      liftMobileHigherRight, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor, port5,      liftConeRight, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor, port6,      liftConeLeft, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor, port7,      liftMobileHigherLeft, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor, port8,      liftMobileLowerLeft, tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_3)
#pragma config(Motor, port9,      driveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor, port10,     driveBackLeft, tmotorVex393HighSpeed_HBridge, openLoop, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard        !!*//
​
#pragma DebuggerWindows("Sensors")
#pragma DebuggerWindows("Motors")
#pragma DebuggerWindows("Locals")
#pragma DebuggerWindows("Globals")
​
// main
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}



task usercontrol()
{

	//enable mobile mode as default mode
	bool mobileLiftMode = true;

	// main loop
	while (true)
	{

		//mode switching from mobile mode(default mode) or cone lift mode
		if(vexRT[Btn8D] == 1){ // if button 8 down,
			mobileLiftMode = false;
		}
		else if(vexRT[Btn8R] == 1){
			mobileLiftMode = true;
		}

		if(mobileMode == true){
			mobileLiftMode();
		}else{
			goalLiftMode();
		}

	}// end main while()
}// task usercontrol()

/*
*	This activate the mobile lift modes
*Default mode
*/
void mobileLiftMode(){

		// lift system control.
		armControl(motor[liftMobileLowerLeft],vexRT[Btn5U],vexRT[Btn5D],50);
		armControl(motor[liftMobileLowerRight],vexRT[Btn5U],vexRT[Btn5D],50);
		armControl(motor[liftMobileHigherLeft],vexRT[Btn6U],vexRT[Btn6D],50);
		armControl(motor[liftMobileHigherRight],vexRT[Btn6U],vexRT[Btn6D],50);
}// end mobile lift mode

/*
*This function activate the oal lift mode.
*/
void goalLiftMode(){
		armControl(motor[liftConeRight]),vexRT[Btn6U],vexRT[Btn6D],50);
		armControl(motor[liftConeLeft]),vexRT[Btn6U],vexRT[Btn6D],50);
}// end goal lift mode
