#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftAngleRight, sensorPotentiometer)
#pragma config(Sensor, in2,    liftAngleLeft,  sensorPotentiometer)
#pragma config(Sensor, in3,    coneAngleRight, sensorPotentiometer)
#pragma config(Sensor, in4,    coneAngleLeft,  sensorPotentiometer)
#pragma config(Sensor, in5,    lineLeft,       sensorNone)
#pragma config(Sensor, in6,    lineRight,      sensorNone)
#pragma config(Sensor, in7,    lineBack,       sensorNone)
#pragma config(Sensor, dgtl1,  extendLeft,     sensorDigitalOut)
#pragma config(Sensor, dgtl2,  extendRight,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  coneLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl4,  mobleGoalLower, sensorTouch)
#pragma config(Sensor, dgtl5,  mobleGoalHigher, sensorTouch)
#pragma config(Sensor, I2C_1,  liftLowerRight, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  liftLowerLeft,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  leftDrive,      sensorNone)
#pragma config(Sensor, I2C_4,  rightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveTrainRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           liftMobileLowerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port4,           liftMobileHigherRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftConeRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           liftConeLeft,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftMobileHigherLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveTrainLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftMobileLowerLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          coneIntake,    tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")
#pragma DebuggerWindows("Motors")
#pragma DebuggerWindows("Locals")
#pragma DebuggerWindows("Globals")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//bool mobileLowerIfTrue = true;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...






}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int testCase = 0 ;

	while(1){
		if(vexRT[Btn8U] == 1){
			testCase = 1;
		}
		else if(vexRT[Btn8D] == 1){
			testCase = 2;
		}else if(vexRT[Btn8R] == 1){
			testCase = 3;
		}else if(vexRT[Btn8L] == 1){
			testCase = 4;
		}else if(vexRT[Btn7U] == 1){
			testCase = 5;
		}else if(vexRT[Btn7D] == 1){
			testCase = 6;
		}else if(vexRT[Btn7R] == 1){
			testCase = 7;
		}

		switch(testCase){
			case 1:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 1000){
		    motor[port2] = 63 ;
		    motor[port8] = 63 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 2:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 1500){
		    motor[port2] = 63 ;
		    motor[port8] = 63 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 3:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 2500){
		    motor[port2] = 63 ;
		    motor[port8] = 63 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 4:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 5000){
		    motor[port2] = 63 ;
		    motor[port8] = 63 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 5:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 5000){
		    motor[port2] = 90 ;
		    motor[port8] = 90 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 6:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 5000){
		    motor[port2] = 110 ;
		    motor[port8] = 110 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;

			case 7:
			// initialize setPID
			setPIDforMotor(driveLeft);
	    setPIDforMotor(driveRight);

			resetMotorEncoder(motor[port2]);
		  resetMotorEncoder(motor[port8]);

		  // go to requested ticks.
		  while(getMotorEncoder(port8) < 5000){
		    motor[port2] = 127 ;
		    motor[port8] = 127 ;
		  }

		  // stop motor
		  motor[port2] = 0;
		  motor[port8] = 0;
		}

		}
	}//e nd while

}
